### ISSUE TITLE
Week 8 Review

### ISSUE THREAD

**Issue by ac7407** [ShihChiangLo/comp-lab-class#6]
Hi ShihChiang, I can see that you have the input files, but maybe you forgot to upload images of your 2D and 3D WCA systems on Github?

**Comment by ShihChiangLo** [comment]
I upload my files to another branch named "newbranch". you can switch to that branch by change the branch from "main" to "newbranch". Sorry for the confusing organization of my results.

**Comment by ac7407** [comment]
No worries!
